# Generated by Django 4.0 on 2021-12-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('first_silver', models.IntegerField()),
                ('first_gold', models.IntegerField()),
                ('hundredth_silver', models.IntegerField()),
                ('hundreth_gold', models.IntegerField()),
            ],
        ),
    ]
