# Generated by Django 4.0 on 2021-12-30 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='first_gold',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='first_silver',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='hundredth_silver',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='hundreth_gold',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField()),
                ('position', models.IntegerField()),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.puzzle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
