# Generated by Django 4.0 on 2021-12-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_puzzle_first_gold_alter_puzzle_first_silver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='part',
            field=models.IntegerField(null=True),
        ),
    ]
