# Generated by Django 4.0 on 2021-12-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_record_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='hundreth_gold',
            new_name='hundredth_gold',
        ),
    ]
